### ISSUE TITLE
Version 0.1

### ISSUE THREAD

**Issue by yoshuawuyts** [jenius/axis#62]
## Features
- [ ] [Position mixins](https://github.com/jenius/axis/issues/59)
- [ ] [Responsive images](https://github.com/jenius/axis/issues/55)
- [x] [Typography](https://github.com/jenius/axis/issues/54)
- [x] [Grid](https://github.com/jenius/axis/pull/49)
## Performance
- [x] [Big fat refactor](https://github.com/jenius/axis/issues/50)
- [ ] [Documentation](https://github.com/jenius/axis/issues/58)
## Bugfixes
- [x] [Base font size in settings](https://github.com/jenius/axis/issues/53)
- [x] [Gradient background vendor prefixing](https://github.com/jenius/axis/issues/26)
- [x] [NPM version badge](https://github.com/jenius/axis/pull/61)
